version: "3"

# DBの永続化
volumes:
  mysql_volume:

# コンテナ間通信
# 事前に以下のコマンドを実行する必要あり
# コマンド: docker network create go_app_network
networks:
  go_app_network:
    external: true

services:
  # MySQL
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - mysql_volume:/var/lib/mysql
    image: go_db
    container_name: go_db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - TZ=Asia/Tokyo
    ports:
      - 3306:3306
    networks:
      - go_app_network

  # Go API
  api:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    image: go_api
    container_name: go_api
    ports:
      - "8080:8000"
    volumes:
      - ./:/app
    depends_on:
      - db
    networks:
      - go_app_network
    environment:
      - GMAIL_ACCOUNT=${GMAIL_ACCOUNT}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
      - _ENV=dev
    tty: true
