### 環境変数
@port = 8080
@hostname = localhost
@host = {{hostname}}:{{port}}
@contentType=application/json

### APIの接続確認用
GET http://{{host}} HTTP/1.1
content-type: {{contentType}}

### すべての本を取得
GET http://{{host}}/books HTTP/1.1
content-type: {{contentType}}

### すべての出版社を取得
GET http://{{host}}/publishers HTTP/1.1
content-type: {{contentType}}

### すべての作家を取得
GET http://{{host}}/authors HTTP/1.1
content-type: {{contentType}}

### 作家を一人取得
GET http://{{host}}/author/1 HTTP/1.1
content-type: {{contentType}}


### JWT を試す
POST http://{{host}}/login HTTP/1.1
Content-Type: {{contentType}}

{
  "user_name": "monshin",
  "password": "monshin"
}

###
GET http://{{host}}/auth/hello HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Njk0NjAxNDYsImlkIjoiYWRtaW4iLCJvcmlnX2lhdCI6MTY2OTQ1NjU0Nn0.5P-518WDWBYUHKIR18nqUybUfcgCBPyrGQdX-OvBa9s
Content-Type: {{contentType}}

###
# @name signup
# @prompt username
# @prompt password
POST http://{{host}}/lobby/signup HTTP/1.1
Content-Type: {{contentType}}

{
  "user_name": "{{username}}",
  "password": "{{password}}"
}

###
# @name login
# @prompt username
# @prompt password
POST http://{{host}}/lobby/login HTTP/1.1
Content-Type: {{contentType}}

{
  "user_name": "{{username}}",
  "password": "{{password}}"
}


###
# @name validate
@jwt = {{login.response.headers.Jwt}}
GET http://{{host}}/lobby/validate HTTP/1.1
Content-Type: {{contentType}}
Jwt: {{jwt}}
