### 環境変数
@port = 8080
@hostname = localhost
@host = {{hostname}}:{{port}}
@contentType=application/json

### APIの接続確認用
GET http://{{host}} HTTP/1.1
content-type: {{contentType}}

### すべての本を取得
GET http://{{host}}/books HTTP/1.1
content-type: {{contentType}}

### すべての出版社を取得
GET http://{{host}}/publishers HTTP/1.1
content-type: {{contentType}}

### すべての作家を取得
GET http://{{host}}/authors HTTP/1.1
content-type: {{contentType}}

### 作家を一人取得
GET http://{{host}}/author/1 HTTP/1.1
content-type: {{contentType}}

### ユーザーを登録する
POST http://{{host}}/api/v1/signup HTTP/1.1
content-type: {{contentType}}

{
  "user_id": "ibc365dev",
  "name": "ibc開発用アカウント",
  "email": "dev@ibc.co.jp",
  "password": "123456789"
}

### ログインする
POST http://{{host}}/api/v1/signin HTTP/1.1
Content-Type: {{contentType}}

{
  "user_id": "ibc365dev",
  "password": "123456789"
}